# Copyright (c) 2021-present The Torchy Authors.
# Distributed under the MIT license that can be found in the LICENSE file.

type_inference = {
  '__lshift__.Tensor': 'EQ_PROMOTED',
  '__rshift__.Tensor': 'EQ_PROMOTED',
  '_add_relu.Tensor': 'EQ_PROMOTED',
  '_add_relu_.Tensor': 'EQ_PROMOTED',
  '_cast_Byte': 'ALL Byte',
  '_cast_Char': 'ALL Char',
  '_cast_Double': 'ALL Double',
  '_cast_Float': 'ALL Float',
  '_cast_Half': 'ALL Half',
  '_cast_Int': 'ALL Int',
  '_cast_Long': 'ALL Long',
  '_cast_Short': 'ALL Short',
  '_gather_sparse_backward': 'EQ_THIRD',
  '_make_per_channel_quantized_tensor': 'TO_QINT',
  '_make_per_tensor_quantized_tensor': 'TO_QINT',
  '_s_where': 'EQ_SECOND',
  '_shape_as_tensor': 'ALL Long',
  '_stack': 'EQ_PROMOTED',
  '_test_ambiguous_defaults.a': 'ALL Long',
  '_test_serialization_subcmul': 'BOOL2INT2',
  '_view_as_real_physical': 'TO_VALUE_TYPE',
  'abs': 'TO_VALUE_TYPE',
  'absolute': 'TO_VALUE_TYPE',
  'acos': 'TO_FLOAT',
  'acosh': 'TO_FLOAT',
  'add.Scalar': 'BOOL2INT',
  'add.Tensor': 'EQ_PROMOTED',
  'addr': 'EQ_PROMOTED',
  'all': 'BOOLBYTE',
  'angle': 'TO_REAL_FLOAT',
  'any': 'BOOLBYTE',
  'arccos': 'TO_FLOAT',
  'arccosh': 'TO_FLOAT',
  'arcsin': 'TO_FLOAT',
  'arcsinh': 'TO_FLOAT',
  'arctan': 'TO_FLOAT',
  'arctanh': 'TO_FLOAT',
  'argmax': 'ALL Long',
  'argmin': 'ALL Long',
  'asin': 'TO_FLOAT',
  'asinh': 'TO_FLOAT',
  'atan': 'TO_FLOAT',
  'atan2': 'TO_FLOAT2',
  'atanh': 'TO_FLOAT',
  'bernoulli': 'ALL Double',
  'binary_cross_entropy_with_logits': 'EQ_SECOND',
  'binary_cross_entropy_with_logits_backward': 'TO_FLOAT4',
  'bincount': 'TO_FLOAT_DOUBLE',
  'bitwise_left_shift.Tensor': 'EQ_PROMOTED',
  'bitwise_right_shift.Tensor': 'EQ_PROMOTED',
  'block_diag': 'EQ_PROMOTED',
  'bucketize.Scalar': 'ALL Long',
  'bucketize.Tensor': 'ALL Long',
  'column_stack': 'EQ_PROMOTED',
  'complex': 'TO_COMPLEX',
  'copysign.Scalar': 'TO_FLOAT',
  'copysign.Tensor': 'TO_FLOAT2',
  'cos': 'TO_FLOAT',
  'cosh': 'TO_FLOAT',
  'count_nonzero': 'ALL Long',
  'count_nonzero.dim_IntList': 'ALL Long',
  'deg2rad': 'TO_FLOAT',
  'dequantize.self': 'ALL Float',
  'digamma': 'TO_FLOAT',
  'dist': 'TO_REAL2',
  'div.Scalar': 'TO_FLOAT',
  'div.Scalar_mode': 'TO_FLOAT',
  'div.Tensor': 'TO_FLOAT2',
  'div.Tensor_mode': 'TO_FLOAT2',
  'divide.Scalar': 'TO_FLOAT',
  'divide.Scalar_mode': 'TO_FLOAT',
  'divide.Tensor': 'TO_FLOAT2',
  'divide.Tensor_mode': 'TO_FLOAT2',
  'dstack': 'EQ_PROMOTED',
  'elu_backward': 'EQ_PROMOTED',
  'eq.Scalar': 'ALL Bool',
  'eq.Tensor': 'ALL Bool',
  'erf': 'TO_FLOAT',
  'erfc': 'TO_FLOAT',
  'erfinv': 'TO_FLOAT',
  'exp': 'TO_FLOAT',
  'exp2': 'TO_FLOAT',
  'expm1': 'TO_FLOAT',
  'fft_fftn': 'TO_COMPLEX',
  'fft_ifftn': 'TO_COMPLEX',
  'fft_rfftn': 'TO_COMPLEX',
  'flatten_dense_tensors': 'EQ_PROMOTED',
  'float_power.Scalar': 'TO_DOUBLE',
  'float_power.Tensor_Scalar': 'TO_DOUBLE',
  'float_power.Tensor_Tensor': 'TO_DOUBLE2',
  'floor_divide': 'EQ_PROMOTED',
  'fmax': 'EQ_PROMOTED',
  'fmin': 'EQ_PROMOTED',
  'fmod.Tensor': 'EQ_PROMOTED',
  'frobenius_norm': 'TO_VALUE_TYPE',
  'frobenius_norm.dim': 'TO_VALUE_TYPE',
  'gcd': 'EQ_PROMOTED',
  'ge.Scalar': 'ALL Bool',
  'ge.Tensor': 'ALL Bool',
  'gelu_backward': 'EQ_PROMOTED',
  'ger': 'EQ_PROMOTED',
  'greater.Scalar': 'ALL Bool',
  'greater.Tensor': 'ALL Bool',
  'greater_equal.Scalar': 'ALL Bool',
  'greater_equal.Tensor': 'ALL Bool',
  'gt.Scalar': 'ALL Bool',
  'gt.Tensor': 'ALL Bool',
  'hardshrink_backward': 'EQ_PROMOTED',
  'hardsigmoid_backward': 'EQ_PROMOTED',
  'hardswish_backward': 'EQ_PROMOTED',
  'hardtanh_backward': 'EQ_PROMOTED',
  'hstack': 'EQ_PROMOTED',
  'hypot': 'EQ_PROMOTED',
  'i0': 'TO_FLOAT',
  'igamma': 'EQ_PROMOTED',
  'igammac': 'EQ_PROMOTED',
  'imag': 'TO_VALUE_TYPE',
  'infinitely_differentiable_gelu_backward': 'EQ_SECOND',
  'inner': 'EQ_SECOND',
  'isclose': 'ALL Bool',
  'isfinite': 'ALL Bool',
  'isin.Scalar_Tensor': 'ALL Bool',
  'isin.Tensor_Scalar': 'ALL Bool',
  'isin.Tensor_Tensor': 'ALL Bool',
  'isinf': 'ALL Bool',
  'isnan': 'ALL Bool',
  'isneginf': 'ALL Bool',
  'isposinf': 'ALL Bool',
  'isreal': 'ALL Bool',
  'kl_div': 'TO_FLOAT2_2',
  'kron': 'EQ_PROMOTED',
  'l1_loss': 'TO_VALUE_TYPE',
  'l1_loss_backward': 'EQ_SECOND',
  'lcm': 'EQ_PROMOTED',
  'ldexp.Tensor': 'TO_FLOAT2_2',
  'le.Scalar': 'ALL Bool',
  'le.Tensor': 'ALL Bool',
  'leaky_relu_backward': 'EQ_PROMOTED',
  'less.Scalar': 'ALL Bool',
  'less.Tensor': 'ALL Bool',
  'less_equal.Scalar': 'ALL Bool',
  'less_equal.Tensor': 'ALL Bool',
  'lgamma': 'TO_FLOAT',
  'linalg_norm': 'TO_VALUE_TYPE',
  'linalg_vector_norm': 'TO_VALUE_TYPE',
  'log': 'TO_FLOAT',
  'log10': 'TO_FLOAT',
  'log1p': 'TO_FLOAT',
  'log2': 'TO_FLOAT',
  'logaddexp': 'EQ_PROMOTED',
  'logaddexp2': 'EQ_PROMOTED',
  'logical_and': 'ALL Bool',
  'logical_not': 'ALL Bool',
  'logical_or': 'ALL Bool',
  'logical_xor': 'ALL Bool',
  'logit': 'TO_FLOAT',
  'logit_backward': 'EQ_PROMOTED',
  'lt.Scalar': 'ALL Bool',
  'lt.Tensor': 'ALL Bool',
  'margin_ranking_loss': 'TO_FLOAT3',
  'max.other': 'EQ_PROMOTED',
  'maximum': 'EQ_PROMOTED',
  'min.other': 'EQ_PROMOTED',
  'minimum': 'EQ_PROMOTED',
  'mish_backward': 'EQ_SECOND',
  'mse_loss': 'EQ_PROMOTED',
  'mul.Scalar': 'BOOL2INT',
  'mul.Tensor': 'EQ_PROMOTED',
  'multinomial': 'ALL Long',
  'multiply.Scalar': 'BOOL2INT',
  'multiply.Tensor': 'EQ_PROMOTED',
  'mvlgamma': 'TO_FLOAT',
  'nanquantile': 'ALL Double',
  'nansum': 'INTEGRAL2INT',
  'nansum.dim_IntList': 'INTEGRAL2INT',
  'ne.Scalar': 'ALL Bool',
  'ne.Tensor': 'ALL Bool',
  'nextafter': 'EQ_PROMOTED',
  'nll_loss': 'ALL Double',
  'nonzero': 'ALL Long',
  'norm.Scalar': 'TO_VALUE_TYPE',
  'norm.ScalarOpt_dim': 'TO_VALUE_TYPE',
  'not_equal.Scalar': 'ALL Bool',
  'not_equal.Tensor': 'ALL Bool',
  'outer': 'EQ_PROMOTED',
  'poisson': 'ALL Double',
  'poisson_nll_loss': 'TO_FLOAT2_4',
  'polar': 'TO_COMPLEX',
  'polygamma': 'TO_FLOAT',
  'pow.Scalar': 'BOOL2INT',
  'pow.Tensor_Scalar': 'BOOL2INT',
  'pow.Tensor_Tensor': 'EQ_PROMOTED',
  'prod': 'INTEGRAL2INT',
  'quantile': 'ALL Double',
  'rad2deg': 'TO_FLOAT',
  'real': 'TO_VALUE_TYPE',
  'reciprocal': 'TO_FLOAT',
  'remainder.Scalar_Tensor': 'BOOL2INT',
  'remainder.Tensor': 'EQ_PROMOTED',
  'repeat_interleave.self_Tensor': 'ALL Byte',
  'row_stack': 'EQ_PROMOTED',
  'rrelu_with_noise_backward': 'TO_FLOAT2',
  'rsqrt': 'TO_FLOAT',
  'rsub.Tensor': 'EQ_PROMOTED',
  'searchsorted.Scalar': 'ALL Long',
  'searchsorted.Tensor': 'ALL Long',
  'sigmoid': 'TO_FLOAT',
  'sigmoid_backward': 'EQ_PROMOTED',
  'signbit': 'ALL Bool',
  'silu_backward': 'EQ_SECOND',
  'sin': 'TO_FLOAT',
  'sinc': 'TO_FLOAT',
  'sinh': 'TO_FLOAT',
  'smooth_l1_loss': 'EQ_PROMOTED',
  'soft_margin_loss_backward': 'EQ_SECOND',
  'softplus_backward': 'TO_FLOAT2',
  'softshrink_backward': 'EQ_PROMOTED',
  'special_digamma': 'TO_FLOAT',
  'special_entr': 'TO_FLOAT',
  'special_erf': 'TO_FLOAT',
  'special_erfc': 'TO_FLOAT',
  'special_erfcx': 'TO_FLOAT',
  'special_erfinv': 'TO_FLOAT',
  'special_exp2': 'TO_FLOAT',
  'special_expit': 'TO_FLOAT',
  'special_expm1': 'TO_FLOAT',
  'special_gammaln': 'TO_FLOAT',
  'special_i0': 'TO_FLOAT',
  'special_i0e': 'TO_FLOAT',
  'special_i1': 'TO_FLOAT',
  'special_i1e': 'TO_FLOAT',
  'special_log1p': 'TO_FLOAT',
  'special_logit': 'TO_FLOAT',
  'special_ndtr': 'TO_FLOAT',
  'special_ndtri': 'TO_FLOAT',
  'special_psi': 'TO_FLOAT',
  'special_sinc': 'TO_FLOAT',
  'special_xlog1py': 'TO_FLOAT2',
  'special_xlog1py.other_scalar': 'TO_FLOAT',
  'special_xlog1py.self_scalar': 'TO_FLOAT',
  'special_zeta': 'TO_FLOAT2',
  'special_zeta.other_scalar': 'TO_FLOAT',
  'special_zeta.self_scalar': 'TO_FLOAT',
  'sqrt': 'TO_FLOAT',
  'square': 'BOOL2INT',
  'stack': 'EQ_PROMOTED',
  'std': 'TO_VALUE_TYPE',
  'std.correction': 'TO_VALUE_TYPE',
  'std.dim': 'TO_VALUE_TYPE',
  'sub.Tensor': 'EQ_PROMOTED',
  'subtract.Tensor': 'EQ_PROMOTED',
  'sum': 'INTEGRAL2INT',
  'sum.dim_IntList': 'INTEGRAL2INT',
  'sum_to_size': 'INTEGRAL2INT',
  'tan': 'TO_FLOAT',
  'tanh': 'TO_FLOAT',
  'tanh_backward': 'EQ_PROMOTED',
  'threshold_backward': 'EQ_PROMOTED',
  'to.device': 'ALL Byte',
  'to.dtype': 'ALL Byte',
  'to.other': 'EQ_SECOND',
  'true_divide.Scalar': 'TO_FLOAT',
  'true_divide.Tensor': 'TO_FLOAT2',
  'type_as': 'EQ_SECOND',
  'vander': 'INTEGRAL2INT',
  'var': 'TO_VALUE_TYPE',
  'var.correction': 'TO_VALUE_TYPE',
  'var.dim': 'TO_VALUE_TYPE',
  'view.dtype': 'ALL Byte',
  'view_as_real': 'TO_VALUE_TYPE',
  'vstack': 'EQ_PROMOTED',
  'where.Scalar': 'ALL Long',
  'where.ScalarOther': 'ALL Long',
  'where.ScalarSelf': 'ALL Long',
  'where.self': 'EQ_SECOND',
  'xlogy.Scalar_Other': 'TO_FLOAT',
  'xlogy.Scalar_Self': 'TO_FLOAT',
  'xlogy.Tensor': 'TO_FLOAT2',
}
