# Copyright (c) 2021-present The Torchy Authors.
# Distributed under the MIT license that can be found in the LICENSE file.

type_inference = {
  '__and__.Scalar': 'BOOL2INT',
  '__and__.Tensor': 'EQ_PROMOTED_CONST',
  '__lshift__.Tensor': 'EQ_PROMOTED_CONST',
  '__or__.Scalar': 'BOOL2INT',
  '__or__.Tensor': 'EQ_PROMOTED_CONST',
  '__rshift__.Tensor': 'EQ_PROMOTED_CONST',
  '__xor__.Scalar': 'BOOL2INT',
  '__xor__.Tensor': 'EQ_PROMOTED_CONST',
  '_add_relu.Scalar': 'BOOL2INT',
  '_add_relu.Tensor': 'EQ_PROMOTED_CONST',
  '_add_relu.out': 'TO_REAL2',
  '_add_relu_.Tensor': 'EQ_PROMOTED_CONST',
  '_cast_Byte': 'ALL Byte',
  '_cast_Char': 'ALL Char',
  '_cast_Double': 'ALL Double',
  '_cast_Float': 'ALL Float',
  '_cast_Half': 'ALL Half',
  '_cast_Int': 'ALL Int',
  '_cast_Long': 'ALL Long',
  '_cast_Short': 'ALL Short',
  '_convert_indices_from_coo_to_csr': 'ALL Long',
  '_convert_indices_from_coo_to_csr.out': 'ALL Long',
  '_gather_sparse_backward': 'EQ_THIRD',
  '_make_per_channel_quantized_tensor': 'TO_QINT',
  '_make_per_tensor_quantized_tensor': 'TO_QINT',
  '_s_where': 'EQ_SECOND',
  '_shape_as_tensor': 'ALL Long',
  '_stack': 'EQ_PROMOTED',
  '_stack.out': 'EQ_THIRD',
  '_test_ambiguous_defaults.a': 'ALL Long',
  '_test_serialization_subcmul': 'BOOL2INT2',
  '_to_copy': 'OPTIONAL_OR21',
  'abs': 'TO_VALUE_TYPE',
  'abs.out': 'EQ_SECOND',
  'absolute': 'TO_VALUE_TYPE',
  'absolute.out': 'EQ_SECOND',
  'acos': 'TO_FLOAT',
  'acos.out': 'EQ_SECOND',
  'acosh': 'TO_FLOAT',
  'acosh.out': 'EQ_SECOND',
  'add.Scalar': 'BOOL2INT',
  'add.Tensor': 'EQ_PROMOTED_BUGGY',
  'add.out': 'EQ_THIRD',
  'addr': 'EQ_PROMOTED',
  'addr.out': 'EQ_FOURTH',
  'all': 'BOOLBYTE',
  'angle': 'TO_REAL_FLOAT',
  'angle.out': 'EQ_SECOND',
  'any': 'BOOLBYTE',
  'arange': 'FIRST_OR_LONG',
  'arange.start': 'FIRST_OR_LONG',
  'arccos': 'TO_FLOAT',
  'arccos.out': 'EQ_SECOND',
  'arccosh': 'TO_FLOAT',
  'arccosh.out': 'EQ_SECOND',
  'arcsin': 'TO_FLOAT',
  'arcsin.out': 'EQ_SECOND',
  'arcsinh': 'TO_FLOAT',
  'arcsinh.out': 'EQ_SECOND',
  'arctan': 'TO_FLOAT',
  'arctan.out': 'EQ_SECOND',
  'arctanh': 'TO_FLOAT',
  'arctanh.out': 'EQ_SECOND',
  'argmax': 'ALL Long',
  'argmax.out': 'ALL Long',
  'argmin': 'ALL Long',
  'argmin.out': 'ALL Long',
  'argsort': 'ALL Long',
  'asin': 'TO_FLOAT',
  'asin.out': 'EQ_SECOND',
  'asinh': 'TO_FLOAT',
  'asinh.out': 'EQ_SECOND',
  'atan': 'TO_FLOAT',
  'atan.out': 'EQ_SECOND',
  'atan2': 'TO_FLOAT2',
  'atan2.out': 'EQ_THIRD',
  'atanh': 'TO_FLOAT',
  'atanh.out': 'EQ_SECOND',
  'bartlett_window': 'FIRST_OR_DEFAULT',
  'bartlett_window.periodic': 'FIRST_OR_DEFAULT',
  'bernoulli.out': 'EQ_SECOND',
  'binary_cross_entropy_with_logits': 'EQ_SECOND',
  'binary_cross_entropy_with_logits_backward': 'TO_FLOAT4',
  'bincount': 'TO_FLOAT_DOUBLE',
  'bitwise_and.Scalar': 'BOOL2INT',
  'bitwise_and.Scalar_out': 'EQ_SECOND',
  'bitwise_and.Tensor': 'EQ_PROMOTED_CONST',
  'bitwise_and.Tensor_out': 'EQ_THIRD',
  'bitwise_left_shift.Tensor': 'EQ_PROMOTED_CONST',
  'bitwise_left_shift.Tensor_Scalar_out': 'EQ_SECOND',
  'bitwise_left_shift.Tensor_out': 'EQ_THIRD',
  'bitwise_or.Scalar': 'BOOL2INT',
  'bitwise_or.Scalar_out': 'EQ_SECOND',
  'bitwise_or.Tensor': 'EQ_PROMOTED_CONST',
  'bitwise_or.Tensor_out': 'EQ_THIRD',
  'bitwise_right_shift.Tensor': 'EQ_PROMOTED_CONST',
  'bitwise_right_shift.Tensor_Scalar_out': 'EQ_SECOND',
  'bitwise_right_shift.Tensor_out': 'EQ_THIRD',
  'bitwise_xor.Scalar': 'BOOL2INT',
  'bitwise_xor.Scalar_out': 'EQ_SECOND',
  'bitwise_xor.Tensor': 'EQ_PROMOTED_CONST',
  'bitwise_xor.Tensor_out': 'EQ_THIRD',
  'blackman_window': 'FIRST_OR_DEFAULT',
  'blackman_window.periodic': 'FIRST_OR_DEFAULT',
  'block_diag': 'EQ_PROMOTED',
  'bucketize.Scalar': 'ALL Long',
  'bucketize.Tensor': 'ALL Long',
  'bucketize.Tensor_out': 'ALL Long',
  'clamp.Tensor_out': 'EQ_FOURTH',
  'clamp_max.Tensor_out': 'EQ_THIRD',
  'clamp_min.Tensor_out': 'EQ_THIRD',
  'clip.Tensor_out': 'EQ_FOURTH',
  'column_stack': 'EQ_PROMOTED',
  'column_stack.out': 'EQ_THIRD',
  'complex': 'TO_COMPLEX',
  'complex.out': 'EQ_THIRD',
  'copysign.Scalar': 'TO_FLOAT',
  'copysign.Scalar_out': 'EQ_SECOND',
  'copysign.Tensor': 'TO_FLOAT2',
  'copysign.out': 'EQ_THIRD',
  'corrcoef': 'TO_FLOAT',
  'cos': 'TO_FLOAT',
  'cos.out': 'EQ_SECOND',
  'cosh': 'TO_FLOAT',
  'cosh.out': 'EQ_SECOND',
  'count_nonzero': 'ALL Long',
  'count_nonzero.dim_IntList': 'ALL Long',
  'deg2rad': 'TO_FLOAT',
  'deg2rad.out': 'EQ_SECOND',
  'dequantize.self': 'ALL Float',
  'digamma': 'TO_FLOAT',
  'digamma.out': 'EQ_SECOND',
  'dist': 'TO_REAL2',
  'div.Scalar': 'TO_FLOAT',
  'div.Scalar_mode': 'TO_FLOAT',
  'div.Tensor': 'TO_FLOAT2',
  'div.Tensor_mode': 'TO_FLOAT2',
  'div.out': 'EQ_THIRD',
  'div.out_mode': 'EQ_THIRD',
  'divide.Scalar': 'TO_FLOAT',
  'divide.Scalar_mode': 'TO_FLOAT',
  'divide.Tensor': 'TO_FLOAT2',
  'divide.Tensor_mode': 'TO_FLOAT2',
  'divide.out': 'EQ_THIRD',
  'divide.out_mode': 'EQ_THIRD',
  'dstack': 'EQ_PROMOTED',
  'dstack.out': 'EQ_THIRD',
  'elu_backward': 'EQ_PROMOTED_CONST',
  'elu_backward.grad_input': 'EQ_THIRD',
  'empty.memory_format': 'FIRST_OR_DEFAULT',
  'empty.names': 'FIRST_OR_DEFAULT',
  'empty_like': 'OPTIONAL_OR21',
  'empty_strided': 'FIRST_OR_DEFAULT',
  'eq.Scalar': 'ALL Bool',
  'eq.Scalar_out': 'EQ_SECOND',
  'eq.Tensor': 'ALL Bool',
  'eq.Tensor_out': 'EQ_THIRD',
  'erf': 'TO_FLOAT',
  'erf.out': 'EQ_SECOND',
  'erfc': 'TO_FLOAT',
  'erfc.out': 'EQ_SECOND',
  'erfinv': 'TO_FLOAT',
  'erfinv.out': 'EQ_SECOND',
  'exp': 'TO_FLOAT',
  'exp.out': 'EQ_SECOND',
  'exp2': 'TO_FLOAT',
  'exp2.out': 'EQ_SECOND',
  'expm1': 'TO_FLOAT',
  'expm1.out': 'EQ_SECOND',
  'eye': 'FIRST_OR_DEFAULT',
  'eye.m': 'FIRST_OR_DEFAULT',
  'fft_fftfreq': 'TO_REAL_FLOAT',
  'fft_fftn': 'TO_COMPLEX',
  'fft_fftn.out': 'EQ_SECOND',
  'fft_ifftn': 'TO_COMPLEX',
  'fft_ifftn.out': 'EQ_SECOND',
  'fft_rfftfreq': 'TO_REAL_FLOAT',
  'fft_rfftn': 'TO_COMPLEX',
  'fft_rfftn.out': 'EQ_SECOND',
  'flatten_dense_tensors': 'EQ_PROMOTED',
  'float_power.Scalar': 'TO_DOUBLE',
  'float_power.Scalar_out': 'EQ_SECOND',
  'float_power.Tensor_Scalar': 'TO_DOUBLE',
  'float_power.Tensor_Scalar_out': 'EQ_SECOND',
  'float_power.Tensor_Tensor': 'TO_DOUBLE2',
  'float_power.Tensor_Tensor_out': 'EQ_THIRD',
  'floor_divide': 'EQ_PROMOTED_CONST',
  'floor_divide.out': 'EQ_THIRD',
  'fmax': 'EQ_PROMOTED_CONST',
  'fmax.out': 'EQ_THIRD',
  'fmin': 'EQ_PROMOTED_CONST',
  'fmin.out': 'EQ_THIRD',
  'fmod.Scalar_out': 'EQ_SECOND',
  'fmod.Tensor': 'EQ_PROMOTED_CONST',
  'fmod.Tensor_out': 'EQ_THIRD',
  'frobenius_norm': 'TO_VALUE_TYPE',
  'frobenius_norm.dim': 'TO_VALUE_TYPE',
  'frobenius_norm.out': 'EQ_SECOND',
  'from_file': 'FIRST_OR_DEFAULT',
  'full': 'FIRST_OR_LONG',
  'full.names': 'FIRST_OR_LONG',
  'full_like': 'OPTIONAL_OR21',
  'fused_moving_avg_obs_fake_quant': 'ALL Float',
  'gcd': 'EQ_PROMOTED_CONST',
  'gcd.out': 'EQ_THIRD',
  'ge.Scalar': 'ALL Bool',
  'ge.Scalar_out': 'EQ_SECOND',
  'ge.Tensor': 'ALL Bool',
  'ge.Tensor_out': 'EQ_THIRD',
  'gelu_backward': 'EQ_PROMOTED_CONST',
  'gelu_backward.grad_input': 'EQ_THIRD',
  'ger': 'EQ_PROMOTED',
  'ger.out': 'EQ_THIRD',
  'greater.Scalar': 'ALL Bool',
  'greater.Scalar_out': 'EQ_SECOND',
  'greater.Tensor': 'ALL Bool',
  'greater.Tensor_out': 'EQ_THIRD',
  'greater_equal.Scalar': 'ALL Bool',
  'greater_equal.Scalar_out': 'EQ_SECOND',
  'greater_equal.Tensor': 'ALL Bool',
  'greater_equal.Tensor_out': 'EQ_THIRD',
  'gt.Scalar': 'ALL Bool',
  'gt.Scalar_out': 'EQ_SECOND',
  'gt.Tensor': 'ALL Bool',
  'gt.Tensor_out': 'EQ_THIRD',
  'hamming_window': 'FIRST_OR_DEFAULT',
  'hamming_window.periodic': 'FIRST_OR_DEFAULT',
  'hamming_window.periodic_alpha': 'FIRST_OR_DEFAULT',
  'hamming_window.periodic_alpha_beta': 'FIRST_OR_DEFAULT',
  'hann_window': 'FIRST_OR_DEFAULT',
  'hann_window.periodic': 'FIRST_OR_DEFAULT',
  'hardshrink_backward': 'EQ_PROMOTED_CONST',
  'hardshrink_backward.grad_input': 'EQ_THIRD',
  'hardsigmoid_backward': 'EQ_PROMOTED_CONST',
  'hardsigmoid_backward.grad_input': 'EQ_THIRD',
  'hardswish_backward': 'EQ_PROMOTED_CONST',
  'hardtanh_backward': 'EQ_PROMOTED_CONST',
  'hardtanh_backward.grad_input': 'EQ_THIRD',
  'hstack': 'EQ_PROMOTED',
  'hstack.out': 'EQ_THIRD',
  'huber_loss.out': 'EQ_THIRD',
  'hypot': 'EQ_PROMOTED_CONST',
  'hypot.out': 'EQ_THIRD',
  'i0': 'TO_FLOAT',
  'i0.out': 'EQ_SECOND',
  'igamma': 'EQ_PROMOTED_CONST',
  'igamma.out': 'EQ_THIRD',
  'igammac': 'EQ_PROMOTED_CONST',
  'igammac.out': 'EQ_THIRD',
  'imag': 'TO_VALUE_TYPE',
  'infinitely_differentiable_gelu_backward': 'EQ_SECOND',
  'inner': 'EQ_PROMOTED_BUGGY',
  'inner.out': 'EQ_THIRD',
  'isclose': 'ALL Bool',
  'isfinite': 'ALL Bool',
  'isin.Scalar_Tensor': 'ALL Bool',
  'isin.Scalar_Tensor_out': 'ALL Bool',
  'isin.Tensor_Scalar': 'ALL Bool',
  'isin.Tensor_Scalar_out': 'ALL Bool',
  'isin.Tensor_Tensor': 'ALL Bool',
  'isin.Tensor_Tensor_out': 'ALL Bool',
  'isinf': 'ALL Bool',
  'isnan': 'ALL Bool',
  'isneginf': 'ALL Bool',
  'isneginf.out': 'ALL Bool',
  'isposinf': 'ALL Bool',
  'isposinf.out': 'ALL Bool',
  'isreal': 'ALL Bool',
  'kaiser_window': 'FIRST_OR_DEFAULT',
  'kaiser_window.beta': 'FIRST_OR_DEFAULT',
  'kaiser_window.periodic': 'FIRST_OR_DEFAULT',
  'kron': 'EQ_PROMOTED',
  'kron.out': 'EQ_THIRD',
  'l1_loss': 'TO_VALUE_TYPE',
  'l1_loss.out': 'EQ_THIRD',
  'l1_loss_backward': 'EQ_SECOND',
  'l1_loss_backward.grad_input': 'EQ_FOURTH',
  'lcm': 'EQ_PROMOTED_CONST',
  'lcm.out': 'EQ_THIRD',
  'ldexp.out': 'EQ_THIRD',
  'le.Scalar': 'ALL Bool',
  'le.Scalar_out': 'EQ_SECOND',
  'le.Tensor': 'ALL Bool',
  'le.Tensor_out': 'EQ_THIRD',
  'leaky_relu_backward': 'EQ_PROMOTED_CONST',
  'leaky_relu_backward.grad_input': 'EQ_THIRD',
  'less.Scalar': 'ALL Bool',
  'less.Scalar_out': 'EQ_SECOND',
  'less.Tensor': 'ALL Bool',
  'less.Tensor_out': 'EQ_THIRD',
  'less_equal.Scalar': 'ALL Bool',
  'less_equal.Scalar_out': 'EQ_SECOND',
  'less_equal.Tensor': 'ALL Bool',
  'less_equal.Tensor_out': 'EQ_THIRD',
  'lgamma': 'TO_FLOAT',
  'lgamma.out': 'EQ_SECOND',
  'linalg_norm.out': 'EQ_FOURTH',
  'linalg_tensorinv.out': 'EQ_SECOND',
  'linalg_tensorsolve.out': 'EQ_THIRD',
  'linalg_vector_norm.out': 'EQ_THIRD',
  'linspace': 'FIRST_OR_DEFAULT',
  'log': 'TO_FLOAT',
  'log.out': 'EQ_SECOND',
  'log10': 'TO_FLOAT',
  'log10.out': 'EQ_SECOND',
  'log1p': 'TO_FLOAT',
  'log1p.out': 'EQ_SECOND',
  'log2': 'TO_FLOAT',
  'log2.out': 'EQ_SECOND',
  'logaddexp': 'EQ_PROMOTED_CONST',
  'logaddexp.out': 'EQ_THIRD',
  'logaddexp2': 'EQ_PROMOTED_CONST',
  'logaddexp2.out': 'EQ_THIRD',
  'logical_and': 'ALL Bool',
  'logical_and.out': 'EQ_THIRD',
  'logical_not': 'ALL Bool',
  'logical_not.out': 'EQ_SECOND',
  'logical_or': 'ALL Bool',
  'logical_or.out': 'EQ_THIRD',
  'logical_xor': 'ALL Bool',
  'logical_xor.out': 'EQ_THIRD',
  'logit': 'TO_FLOAT',
  'logit.out': 'EQ_SECOND',
  'logit_backward': 'EQ_PROMOTED_CONST',
  'logit_backward.grad_input': 'EQ_THIRD',
  'logspace': 'FIRST_OR_DEFAULT',
  'logsumexp.out': 'EQ_SECOND',
  'lt.Scalar': 'ALL Bool',
  'lt.Scalar_out': 'EQ_SECOND',
  'lt.Tensor': 'ALL Bool',
  'lt.Tensor_out': 'EQ_THIRD',
  'margin_ranking_loss': 'TO_FLOAT3',
  'max.other': 'EQ_PROMOTED_CONST',
  'max.out': 'EQ_THIRD',
  'maximum': 'EQ_PROMOTED_CONST',
  'maximum.out': 'EQ_THIRD',
  'mean': 'OPTIONAL_OR21',
  'mean.dim': 'OPTIONAL_OR21',
  'mean.out': 'EQ_THIRD',
  'min.other': 'EQ_PROMOTED_CONST',
  'min.out': 'EQ_THIRD',
  'minimum': 'EQ_PROMOTED_CONST',
  'minimum.out': 'EQ_THIRD',
  'mish_backward': 'EQ_SECOND',
  'mse_loss': 'EQ_PROMOTED_CONST',
  'mse_loss.out': 'EQ_THIRD',
  'msort.out': 'EQ_SECOND',
  'mul.Scalar': 'BOOL2INT',
  'mul.Tensor': 'EQ_PROMOTED_BUGGY',
  'mul.out': 'EQ_THIRD',
  'multinomial': 'ALL Long',
  'multinomial.out': 'ALL Long',
  'multiply.Scalar': 'BOOL2INT',
  'multiply.Tensor': 'EQ_PROMOTED_BUGGY',
  'multiply.out': 'EQ_THIRD',
  'mvlgamma': 'TO_FLOAT',
  'mvlgamma.out': 'EQ_SECOND',
  'nansum': 'OPTIONAL_O21LONG',
  'nansum.IntList_out': 'EQ_THIRD',
  'nansum.dim_IntList': 'OPTIONAL_O21LONG',
  'ne.Scalar': 'ALL Bool',
  'ne.Scalar_out': 'EQ_SECOND',
  'ne.Tensor': 'ALL Bool',
  'ne.Tensor_out': 'EQ_THIRD',
  'new_empty': 'OPTIONAL_OR21',
  'new_empty_strided': 'OPTIONAL_OR21',
  'new_full': 'OPTIONAL_OR21',
  'new_ones': 'OPTIONAL_OR21',
  'new_zeros': 'OPTIONAL_OR21',
  'nextafter': 'EQ_PROMOTED_CONST',
  'nextafter.out': 'EQ_THIRD',
  'nonzero': 'ALL Long',
  'nonzero.out': 'ALL Long',
  'norm.Scalar': 'TO_VALUE_TYPE',
  'norm.ScalarOpt_dim': 'TO_VALUE_TYPE',
  'norm.out': 'EQ_THIRD',
  'normal.Tensor_Tensor_out': 'EQ_THIRD',
  'normal.Tensor_float_out': 'EQ_SECOND',
  'normal.float_Tensor_out': 'EQ_SECOND',
  'normal.float_float': 'FIRST_OR_DEFAULT',
  'not_equal.Scalar': 'ALL Bool',
  'not_equal.Scalar_out': 'EQ_SECOND',
  'not_equal.Tensor': 'ALL Bool',
  'not_equal.Tensor_out': 'EQ_THIRD',
  'ones': 'FIRST_OR_DEFAULT',
  'ones.names': 'FIRST_OR_DEFAULT',
  'ones_like': 'OPTIONAL_OR21',
  'outer': 'EQ_PROMOTED',
  'outer.out': 'EQ_THIRD',
  'polar': 'TO_COMPLEX',
  'polar.out': 'EQ_THIRD',
  'polygamma': 'TO_FLOAT',
  'polygamma.out': 'EQ_SECOND',
  'pow.Scalar': 'BOOL2INT',
  'pow.Scalar_out': 'EQ_SECOND',
  'pow.Tensor_Scalar': 'BOOL2INT',
  'pow.Tensor_Scalar_out': 'EQ_SECOND',
  'pow.Tensor_Tensor': 'EQ_PROMOTED_BUGGY',
  'pow.Tensor_Tensor_out': 'EQ_THIRD',
  'prod': 'OPTIONAL_O21LONG',
  'rad2deg': 'TO_FLOAT',
  'rad2deg.out': 'EQ_SECOND',
  'rand': 'FIRST_OR_DEFAULT',
  'rand.generator': 'FIRST_OR_DEFAULT',
  'rand.generator_with_names': 'FIRST_OR_DEFAULT',
  'rand.names': 'FIRST_OR_DEFAULT',
  'rand_like': 'OPTIONAL_OR21',
  'randint': 'FIRST_OR_DEFAULT',
  'randint.generator': 'FIRST_OR_DEFAULT',
  'randint_like': 'OPTIONAL_OR21',
  'randn': 'FIRST_OR_DEFAULT',
  'randn.generator': 'FIRST_OR_DEFAULT',
  'randn.generator_with_names': 'FIRST_OR_DEFAULT',
  'randn.names': 'FIRST_OR_DEFAULT',
  'randn_like': 'OPTIONAL_OR21',
  'randperm': 'FIRST_OR_LONG',
  'randperm.generator': 'FIRST_OR_LONG',
  'range': 'FIRST_OR_DEFAULT',
  'real': 'TO_VALUE_TYPE',
  'reciprocal': 'TO_FLOAT',
  'reciprocal.out': 'EQ_SECOND',
  'remainder.Scalar_Tensor': 'BOOL2INT',
  'remainder.Scalar_out': 'EQ_SECOND',
  'remainder.Tensor': 'EQ_PROMOTED_CONST',
  'remainder.Tensor_out': 'EQ_THIRD',
  'row_stack': 'EQ_PROMOTED',
  'row_stack.out': 'EQ_THIRD',
  'rrelu_with_noise_backward': 'TO_FLOAT2',
  'rsqrt': 'TO_FLOAT',
  'rsqrt.out': 'EQ_SECOND',
  'rsub.Tensor': 'EQ_PROMOTED_BUGGY',
  'scalar_tensor': 'FIRST_OR_DEFAULT',
  'searchsorted.Scalar': 'ALL Long',
  'searchsorted.Tensor': 'ALL Long',
  'searchsorted.Tensor_out': 'ALL Long',
  'sigmoid': 'TO_FLOAT',
  'sigmoid.out': 'EQ_SECOND',
  'sigmoid_backward': 'EQ_PROMOTED_BUGGY',
  'sigmoid_backward.grad_input': 'EQ_THIRD',
  'signbit': 'ALL Bool',
  'signbit.out': 'ALL Bool',
  'silu_backward': 'EQ_PROMOTED_BUGGY',
  'silu_backward.grad_input': 'EQ_THIRD',
  'sin': 'TO_FLOAT',
  'sin.out': 'EQ_SECOND',
  'sinc': 'TO_FLOAT',
  'sinc.out': 'EQ_SECOND',
  'sinh': 'TO_FLOAT',
  'sinh.out': 'EQ_SECOND',
  'smooth_l1_loss': 'EQ_PROMOTED_CONST',
  'smooth_l1_loss.out': 'EQ_THIRD',
  'smooth_l1_loss_backward': 'EQ_SECOND',
  'smooth_l1_loss_backward.grad_input': 'EQ_FOURTH',
  'soft_margin_loss_backward': 'EQ_SECOND',
  'soft_margin_loss_backward.grad_input': 'EQ_FOURTH',
  'softplus_backward': 'TO_FLOAT2',
  'softplus_backward.grad_input': 'EQ_FOURTH',
  'softshrink_backward': 'EQ_PROMOTED_CONST',
  'softshrink_backward.grad_input': 'EQ_THIRD',
  'sparse_coo_tensor.size': 'FIRST_OR_DEFAULT',
  'special_digamma': 'TO_FLOAT',
  'special_digamma.out': 'EQ_SECOND',
  'special_entr': 'TO_FLOAT',
  'special_entr.out': 'EQ_SECOND',
  'special_erf': 'TO_FLOAT',
  'special_erf.out': 'EQ_SECOND',
  'special_erfc': 'TO_FLOAT',
  'special_erfc.out': 'EQ_SECOND',
  'special_erfcx': 'TO_FLOAT',
  'special_erfcx.out': 'EQ_SECOND',
  'special_erfinv': 'TO_FLOAT',
  'special_erfinv.out': 'EQ_SECOND',
  'special_exp2': 'TO_FLOAT',
  'special_exp2.out': 'EQ_SECOND',
  'special_expit': 'TO_FLOAT',
  'special_expit.out': 'EQ_SECOND',
  'special_expm1': 'TO_FLOAT',
  'special_expm1.out': 'EQ_SECOND',
  'special_gammaln': 'TO_FLOAT',
  'special_gammaln.out': 'EQ_SECOND',
  'special_i0': 'TO_FLOAT',
  'special_i0.out': 'EQ_SECOND',
  'special_i0e': 'TO_FLOAT',
  'special_i0e.out': 'EQ_SECOND',
  'special_i1': 'TO_FLOAT',
  'special_i1.out': 'EQ_SECOND',
  'special_i1e': 'TO_FLOAT',
  'special_i1e.out': 'EQ_SECOND',
  'special_log1p': 'TO_FLOAT',
  'special_log1p.out': 'EQ_SECOND',
  'special_logit': 'TO_FLOAT',
  'special_logit.out': 'EQ_SECOND',
  'special_logsumexp.out': 'EQ_SECOND',
  'special_multigammaln': 'TO_FLOAT',
  'special_multigammaln.out': 'EQ_SECOND',
  'special_ndtr': 'TO_FLOAT',
  'special_ndtr.out': 'EQ_SECOND',
  'special_ndtri': 'TO_FLOAT',
  'special_ndtri.out': 'EQ_SECOND',
  'special_polygamma': 'TO_FLOAT',
  'special_polygamma.out': 'EQ_SECOND',
  'special_psi': 'TO_FLOAT',
  'special_psi.out': 'EQ_SECOND',
  'special_sinc': 'TO_FLOAT',
  'special_sinc.out': 'EQ_SECOND',
  'special_xlog1py': 'TO_FLOAT2',
  'special_xlog1py.other_scalar': 'TO_FLOAT',
  'special_xlog1py.other_scalar_out': 'EQ_SECOND',
  'special_xlog1py.out': 'EQ_THIRD',
  'special_xlog1py.self_scalar': 'TO_FLOAT',
  'special_xlog1py.self_scalar_out': 'EQ_SECOND',
  'special_xlogy': 'TO_FLOAT2',
  'special_xlogy.other_scalar': 'TO_FLOAT',
  'special_xlogy.other_scalar_out': 'EQ_SECOND',
  'special_xlogy.out': 'EQ_THIRD',
  'special_xlogy.self_scalar': 'TO_FLOAT',
  'special_xlogy.self_scalar_out': 'EQ_SECOND',
  'special_zeta': 'TO_FLOAT2',
  'special_zeta.other_scalar': 'TO_FLOAT',
  'special_zeta.other_scalar_out': 'EQ_SECOND',
  'special_zeta.out': 'EQ_THIRD',
  'special_zeta.self_scalar': 'TO_FLOAT',
  'special_zeta.self_scalar_out': 'EQ_SECOND',
  'sqrt': 'TO_FLOAT',
  'sqrt.out': 'EQ_SECOND',
  'square': 'BOOL2INT',
  'square.out': 'EQ_SECOND',
  'stack': 'EQ_PROMOTED',
  'stack.out': 'EQ_THIRD',
  'std': 'TO_VALUE_TYPE',
  'std.correction': 'TO_VALUE_TYPE',
  'std.correction_out': 'EQ_SECOND',
  'std.dim': 'TO_VALUE_TYPE',
  'std.out': 'EQ_SECOND',
  'sub.Tensor': 'EQ_PROMOTED_BUGGY',
  'sub.out': 'EQ_THIRD',
  'subtract.Tensor': 'EQ_PROMOTED_BUGGY',
  'subtract.out': 'EQ_THIRD',
  'sum': 'OPTIONAL_O21LONG',
  'sum.IntList_out': 'EQ_THIRD',
  'sum.dim_IntList': 'OPTIONAL_O21LONG',
  'sum_to_size': 'INTEGRAL2INT',
  'tan': 'TO_FLOAT',
  'tan.out': 'EQ_SECOND',
  'tanh': 'TO_FLOAT',
  'tanh.out': 'EQ_SECOND',
  'tanh_backward': 'EQ_PROMOTED_BUGGY',
  'tanh_backward.grad_input': 'EQ_THIRD',
  'threshold.out': 'EQ_SECOND',
  'threshold_backward': 'EQ_PROMOTED_CONST',
  'threshold_backward.grad_input': 'EQ_THIRD',
  'to.device': 'ALL Byte',
  'to.dtype': 'ALL Byte',
  'to.dtype_layout': 'OPTIONAL_OR21',
  'to.other': 'EQ_SECOND',
  'tril_indices': 'FIRST_OR_LONG',
  'triu_indices': 'FIRST_OR_LONG',
  'true_divide.Scalar': 'TO_FLOAT',
  'true_divide.Tensor': 'TO_FLOAT2',
  'true_divide.out': 'EQ_THIRD',
  'type_as': 'EQ_SECOND',
  'vander': 'INTEGRAL2INT',
  'var': 'TO_VALUE_TYPE',
  'var.correction': 'TO_VALUE_TYPE',
  'var.correction_out': 'EQ_SECOND',
  'var.dim': 'TO_VALUE_TYPE',
  'var.out': 'EQ_SECOND',
  'view.dtype': 'ALL Byte',
  'view_as_real': 'TO_VALUE_TYPE',
  'vstack': 'EQ_PROMOTED',
  'vstack.out': 'EQ_THIRD',
  'where.Scalar': 'ALL Long',
  'where.ScalarOther': 'ALL Long',
  'where.ScalarSelf': 'ALL Long',
  'where.self': 'EQ_SECOND',
  'xlogy.OutScalar_Other': 'EQ_SECOND',
  'xlogy.OutScalar_Self': 'EQ_SECOND',
  'xlogy.OutTensor': 'EQ_THIRD',
  'xlogy.Scalar_Other': 'TO_FLOAT',
  'xlogy.Scalar_Self': 'TO_FLOAT',
  'xlogy.Tensor': 'TO_FLOAT2',
  'zeros': 'FIRST_OR_DEFAULT',
  'zeros.names': 'FIRST_OR_DEFAULT',
  'zeros_like': 'OPTIONAL_OR21',
}

shape_inference = {

}
