# Copyright (c) 2021-present The Torchy Authors.
# Distributed under the MIT license that can be found in the LICENSE file.

type_inference = {
  '__lshift__.Tensor': 'EQ_PROMOTED_CONST',
  '__rshift__.Tensor': 'EQ_PROMOTED_CONST',
  '_add_relu.Tensor': 'EQ_PROMOTED_CONST',
  '_add_relu_.Tensor': 'EQ_PROMOTED_CONST',
  '_cast_Byte': 'ALL Byte',
  '_cast_Char': 'ALL Char',
  '_cast_Double': 'ALL Double',
  '_cast_Float': 'ALL Float',
  '_cast_Half': 'ALL Half',
  '_cast_Int': 'ALL Int',
  '_cast_Long': 'ALL Long',
  '_cast_Short': 'ALL Short',
  '_gather_sparse_backward': 'EQ_THIRD',
  '_make_per_channel_quantized_tensor': 'TO_QINT',
  '_make_per_tensor_quantized_tensor': 'TO_QINT',
  '_s_where': 'EQ_SECOND',
  '_shape_as_tensor': 'ALL Long',
  '_stack': 'EQ_PROMOTED_CONST',
  '_test_ambiguous_defaults.a': 'ALL Long',
  '_test_serialization_subcmul': 'BOOL2INT2',
  '_view_as_real_physical': 'TO_VALUE_TYPE',
  'abs': 'TO_VALUE_TYPE',
  'absolute': 'TO_VALUE_TYPE',
  'acos': 'TO_FLOAT',
  'acosh': 'TO_FLOAT',
  'add.Scalar': 'BOOL2INT',
  'add.Tensor': 'EQ_PROMOTED_BUGGY',
  'all': 'BOOLBYTE',
  'angle': 'TO_REAL_FLOAT',
  'any': 'BOOLBYTE',
  'arccos': 'TO_FLOAT',
  'arccosh': 'TO_FLOAT',
  'arcsin': 'TO_FLOAT',
  'arcsinh': 'TO_FLOAT',
  'arctan': 'TO_FLOAT',
  'arctanh': 'TO_FLOAT',
  'argmax': 'ALL Long',
  'argmin': 'ALL Long',
  'argsort': 'ALL Long',
  'asin': 'TO_FLOAT',
  'asinh': 'TO_FLOAT',
  'atan': 'TO_FLOAT',
  'atan2': 'TO_FLOAT2',
  'atanh': 'TO_FLOAT',
  'binary_cross_entropy_with_logits': 'EQ_SECOND',
  'binary_cross_entropy_with_logits_backward': 'TO_FLOAT4',
  'bincount': 'TO_FLOAT_DOUBLE',
  'bitwise_left_shift.Tensor': 'EQ_PROMOTED_CONST',
  'bitwise_right_shift.Tensor': 'EQ_PROMOTED_CONST',
  'block_diag': 'EQ_PROMOTED_CONST',
  'bucketize.Scalar': 'ALL Long',
  'bucketize.Tensor': 'ALL Long',
  'column_stack': 'EQ_PROMOTED_CONST',
  'complex': 'TO_COMPLEX',
  'copysign.Scalar': 'TO_FLOAT',
  'copysign.Tensor': 'TO_FLOAT2',
  'cos': 'TO_FLOAT',
  'cosh': 'TO_FLOAT',
  'count_nonzero': 'ALL Long',
  'count_nonzero.dim_IntList': 'ALL Long',
  'deg2rad': 'TO_FLOAT',
  'dequantize.self': 'ALL Float',
  'digamma': 'TO_FLOAT',
  'dist': 'TO_REAL2',
  'div.Scalar': 'TO_FLOAT',
  'div.Scalar_mode': 'TO_FLOAT',
  'div.Tensor': 'TO_FLOAT2',
  'div.Tensor_mode': 'TO_FLOAT2',
  'divide.Scalar': 'TO_FLOAT',
  'divide.Scalar_mode': 'TO_FLOAT',
  'divide.Tensor': 'TO_FLOAT2',
  'divide.Tensor_mode': 'TO_FLOAT2',
  'dstack': 'EQ_PROMOTED_CONST',
  'elu_backward': 'EQ_PROMOTED_CONST',
  'eq.Scalar': 'ALL Bool',
  'eq.Tensor': 'ALL Bool',
  'erf': 'TO_FLOAT',
  'erfc': 'TO_FLOAT',
  'erfinv': 'TO_FLOAT',
  'exp': 'TO_FLOAT',
  'exp2': 'TO_FLOAT',
  'expm1': 'TO_FLOAT',
  'fft_fftn': 'TO_COMPLEX',
  'fft_ifftn': 'TO_COMPLEX',
  'fft_rfftn': 'TO_COMPLEX',
  'flatten_dense_tensors': 'EQ_PROMOTED_CONST',
  'float_power.Scalar': 'TO_DOUBLE',
  'float_power.Tensor_Scalar': 'TO_DOUBLE',
  'float_power.Tensor_Tensor': 'TO_DOUBLE2',
  'floor_divide': 'EQ_PROMOTED_CONST',
  'fmax': 'EQ_PROMOTED_CONST',
  'fmin': 'EQ_PROMOTED_CONST',
  'fmod.Tensor': 'EQ_PROMOTED_CONST',
  'frobenius_norm': 'TO_VALUE_TYPE',
  'frobenius_norm.dim': 'TO_VALUE_TYPE',
  'gcd': 'EQ_PROMOTED_CONST',
  'ge.Scalar': 'ALL Bool',
  'ge.Tensor': 'ALL Bool',
  'gelu_backward': 'EQ_PROMOTED_CONST',
  'ger': 'EQ_PROMOTED_CONST',
  'greater.Scalar': 'ALL Bool',
  'greater.Tensor': 'ALL Bool',
  'greater_equal.Scalar': 'ALL Bool',
  'greater_equal.Tensor': 'ALL Bool',
  'gt.Scalar': 'ALL Bool',
  'gt.Tensor': 'ALL Bool',
  'hardshrink_backward': 'EQ_PROMOTED_CONST',
  'hardsigmoid_backward': 'EQ_PROMOTED_CONST',
  'hardswish_backward': 'EQ_PROMOTED_CONST',
  'hardtanh_backward': 'EQ_PROMOTED_CONST',
  'hstack': 'EQ_PROMOTED_CONST',
  'hypot': 'EQ_PROMOTED_CONST',
  'i0': 'TO_FLOAT',
  'igamma': 'EQ_PROMOTED_CONST',
  'igammac': 'EQ_PROMOTED_CONST',
  'imag': 'TO_VALUE_TYPE',
  'infinitely_differentiable_gelu_backward': 'EQ_SECOND',
  'inner': 'EQ_PROMOTED_BUGGY',
  'isclose': 'ALL Bool',
  'isfinite': 'ALL Bool',
  'isin.Scalar_Tensor': 'ALL Bool',
  'isin.Tensor_Scalar': 'ALL Bool',
  'isin.Tensor_Tensor': 'ALL Bool',
  'isinf': 'ALL Bool',
  'isnan': 'ALL Bool',
  'isneginf': 'ALL Bool',
  'isposinf': 'ALL Bool',
  'isreal': 'ALL Bool',
  'kl_div': 'TO_FLOAT2_2',
  'l1_loss': 'TO_VALUE_TYPE',
  'l1_loss_backward': 'EQ_SECOND',
  'lcm': 'EQ_PROMOTED_CONST',
  'ldexp.Tensor': 'TO_FLOAT2_2',
  'le.Scalar': 'ALL Bool',
  'le.Tensor': 'ALL Bool',
  'leaky_relu_backward': 'EQ_PROMOTED_CONST',
  'less.Scalar': 'ALL Bool',
  'less.Tensor': 'ALL Bool',
  'less_equal.Scalar': 'ALL Bool',
  'less_equal.Tensor': 'ALL Bool',
  'lgamma': 'TO_FLOAT',
  'linalg_norm': 'TO_VALUE_TYPE',
  'linalg_vector_norm': 'TO_VALUE_TYPE',
  'log': 'TO_FLOAT',
  'log10': 'TO_FLOAT',
  'log1p': 'TO_FLOAT',
  'log2': 'TO_FLOAT',
  'logaddexp': 'EQ_PROMOTED_CONST',
  'logaddexp2': 'EQ_PROMOTED_CONST',
  'logical_and': 'ALL Bool',
  'logical_not': 'ALL Bool',
  'logical_or': 'ALL Bool',
  'logical_xor': 'ALL Bool',
  'logit': 'TO_FLOAT',
  'logit_backward': 'EQ_PROMOTED_CONST',
  'lt.Scalar': 'ALL Bool',
  'lt.Tensor': 'ALL Bool',
  'margin_ranking_loss': 'TO_FLOAT3',
  'max.other': 'EQ_PROMOTED_CONST',
  'maximum': 'EQ_PROMOTED_CONST',
  'min.other': 'EQ_PROMOTED_CONST',
  'minimum': 'EQ_PROMOTED_CONST',
  'mish_backward': 'EQ_SECOND',
  'mse_loss': 'EQ_PROMOTED_CONST',
  'mul.Scalar': 'BOOL2INT',
  'mul.Tensor': 'EQ_PROMOTED_BUGGY',
  'multinomial': 'ALL Long',
  'multiply.Scalar': 'BOOL2INT',
  'multiply.Tensor': 'EQ_PROMOTED_BUGGY',
  'mvlgamma': 'TO_FLOAT',
  'nansum': 'INTEGRAL2INT',
  'nansum.dim_IntList': 'INTEGRAL2INT',
  'ne.Scalar': 'ALL Bool',
  'ne.Tensor': 'ALL Bool',
  'nextafter': 'EQ_PROMOTED_CONST',
  'nonzero': 'ALL Long',
  'norm.Scalar': 'TO_VALUE_TYPE',
  'norm.ScalarOpt_dim': 'TO_VALUE_TYPE',
  'not_equal.Scalar': 'ALL Bool',
  'not_equal.Tensor': 'ALL Bool',
  'outer': 'EQ_PROMOTED_CONST',
  'poisson_nll_loss': 'TO_FLOAT2_4',
  'polar': 'TO_COMPLEX',
  'polygamma': 'TO_FLOAT',
  'pow.Scalar': 'BOOL2INT',
  'pow.Tensor_Scalar': 'BOOL2INT',
  'pow.Tensor_Tensor': 'EQ_PROMOTED_BUGGY',
  'prod': 'INTEGRAL2INT',
  'rad2deg': 'TO_FLOAT',
  'real': 'TO_VALUE_TYPE',
  'reciprocal': 'TO_FLOAT',
  'remainder.Scalar_Tensor': 'BOOL2INT',
  'remainder.Tensor': 'EQ_PROMOTED_CONST',
  'repeat_interleave.Tensor': 'ALL Int',
  'row_stack': 'EQ_PROMOTED_CONST',
  'rrelu_with_noise_backward': 'TO_FLOAT2',
  'rsqrt': 'TO_FLOAT',
  'rsub.Tensor': 'EQ_PROMOTED_BUGGY',
  'searchsorted.Scalar': 'ALL Long',
  'searchsorted.Tensor': 'ALL Long',
  'sigmoid': 'TO_FLOAT',
  'sigmoid_backward': 'EQ_PROMOTED_BUGGY',
  'signbit': 'ALL Bool',
  'silu_backward': 'EQ_SECOND',
  'sin': 'TO_FLOAT',
  'sinc': 'TO_FLOAT',
  'sinh': 'TO_FLOAT',
  'smooth_l1_loss': 'EQ_PROMOTED_CONST',
  'soft_margin_loss_backward': 'EQ_SECOND',
  'softplus_backward': 'TO_FLOAT2',
  'softshrink_backward': 'EQ_PROMOTED_CONST',
  'special_digamma': 'TO_FLOAT',
  'special_entr': 'TO_FLOAT',
  'special_erf': 'TO_FLOAT',
  'special_erfc': 'TO_FLOAT',
  'special_erfcx': 'TO_FLOAT',
  'special_erfinv': 'TO_FLOAT',
  'special_exp2': 'TO_FLOAT',
  'special_expit': 'TO_FLOAT',
  'special_expm1': 'TO_FLOAT',
  'special_gammaln': 'TO_FLOAT',
  'special_i0': 'TO_FLOAT',
  'special_i0e': 'TO_FLOAT',
  'special_i1': 'TO_FLOAT',
  'special_i1e': 'TO_FLOAT',
  'special_log1p': 'TO_FLOAT',
  'special_logit': 'TO_FLOAT',
  'special_ndtr': 'TO_FLOAT',
  'special_ndtri': 'TO_FLOAT',
  'special_psi': 'TO_FLOAT',
  'special_sinc': 'TO_FLOAT',
  'special_xlog1py': 'TO_FLOAT2',
  'special_xlog1py.other_scalar': 'TO_FLOAT',
  'special_xlog1py.self_scalar': 'TO_FLOAT',
  'special_zeta': 'TO_FLOAT2',
  'special_zeta.other_scalar': 'TO_FLOAT',
  'special_zeta.self_scalar': 'TO_FLOAT',
  'sqrt': 'TO_FLOAT',
  'square': 'BOOL2INT',
  'stack': 'EQ_PROMOTED_CONST',
  'std': 'TO_VALUE_TYPE',
  'std.correction': 'TO_VALUE_TYPE',
  'std.dim': 'TO_VALUE_TYPE',
  'sub.Tensor': 'EQ_PROMOTED_BUGGY',
  'subtract.Tensor': 'EQ_PROMOTED_BUGGY',
  'sum': 'INTEGRAL2INT',
  'sum.dim_IntList': 'INTEGRAL2INT',
  'sum_to_size': 'INTEGRAL2INT',
  'tan': 'TO_FLOAT',
  'tanh': 'TO_FLOAT',
  'tanh_backward': 'EQ_PROMOTED_BUGGY',
  'threshold_backward': 'EQ_PROMOTED_CONST',
  'to.device': 'ALL Byte',
  'to.dtype': 'ALL Byte',
  'to.other': 'EQ_SECOND',
  'true_divide.Scalar': 'TO_FLOAT',
  'true_divide.Tensor': 'TO_FLOAT2',
  'type_as': 'EQ_SECOND',
  'vander': 'INTEGRAL2INT',
  'var': 'TO_VALUE_TYPE',
  'var.correction': 'TO_VALUE_TYPE',
  'var.dim': 'TO_VALUE_TYPE',
  'view.dtype': 'ALL Byte',
  'view_as_real': 'TO_VALUE_TYPE',
  'vstack': 'EQ_PROMOTED_CONST',
  'where.Scalar': 'ALL Long',
  'where.self': 'EQ_SECOND',
  'xlogy.Scalar_Other': 'TO_FLOAT',
  'xlogy.Scalar_Self': 'TO_FLOAT',
  'xlogy.Tensor': 'TO_FLOAT2',
}

shape_inference = {
  '__ilshift__.Scalar': 'EQ_FIRST',
  '__ilshift__.Tensor': 'EQ_FIRST',
  '__irshift__.Scalar': 'EQ_FIRST',
  '__irshift__.Tensor': 'EQ_FIRST',
  '__lshift__.Scalar': 'EQ_FIRST',
  '__lshift__.Tensor': 'STD_PROMOTE',
  '__rshift__.Scalar': 'EQ_FIRST',
  '__rshift__.Tensor': 'STD_PROMOTE',
  '_add_relu.Tensor': 'STD_PROMOTE',
  '_add_relu_.Tensor': 'EQ_FIRST',
  '_cast_Byte': 'EQ_FIRST',
  '_cast_Char': 'EQ_FIRST',
  '_cast_Double': 'EQ_FIRST',
  '_cast_Float': 'EQ_FIRST',
  '_cast_Half': 'EQ_FIRST',
  '_cast_Int': 'EQ_FIRST',
  '_cast_Long': 'EQ_FIRST',
  '_cast_Short': 'EQ_FIRST',
  '_cdist_forward': 'MULT_1ST_2ND',
  '_conj_physical': 'EQ_FIRST',
  '_cumprod': 'EQ_FIRST',
  '_cumsum': 'EQ_FIRST',
  '_dirichlet_grad': 'STD_PROMOTE',
  '_euclidean_dist': 'MULT_1ST_2ND',
  '_fake_quantize_learnable_per_channel_affine': 'EQ_FIRST',
  '_fake_quantize_learnable_per_tensor_affine': 'EQ_FIRST',
  '_gather_sparse_backward': 'EQ_FIRST',
  '_log_softmax': 'EQ_FIRST',
  '_log_softmax_backward_data': 'EQ_FIRST',
  '_logcumsumexp': 'EQ_FIRST',
  '_sample_dirichlet': 'EQ_FIRST',
  '_saturate_weight_to_fp16': 'EQ_FIRST',
  '_softmax': 'EQ_FIRST',
  '_softmax_backward_data': 'EQ_FIRST',
  '_sparse_addmm': 'MATMUL_2ND_3RD',
  '_sparse_mm': 'MUL_1ST_2ND',
  '_standard_gamma': 'EQ_FIRST',
  '_standard_gamma_grad': 'STD_PROMOTE',
  '_test_ambiguous_defaults.a': 'ALL <>',
  '_test_optional_filled_intlist': 'EQ_FIRST',
  '_test_optional_floatlist': 'EQ_FIRST',
  '_test_optional_intlist': 'EQ_FIRST',
  '_test_serialization_subcmul': 'STD_PROMOTE',
  '_trilinear': 'EQ_THIRD',
  '_unsafe_view': 'ALL <>',
  '_weight_norm': 'STD_PROMOTE',
  'abs': 'EQ_FIRST',
  'abs_': 'EQ_FIRST',
  'absolute': 'EQ_FIRST',
  'absolute_': 'EQ_FIRST',
  'acos': 'EQ_FIRST',
  'acos_': 'EQ_FIRST',
  'acosh': 'EQ_FIRST',
  'acosh_': 'EQ_FIRST',
  'add.Scalar': 'EQ_FIRST',
  'add.Tensor': 'STD_PROMOTE',
  'add_.Scalar': 'EQ_FIRST',
  'add_.Tensor': 'EQ_FIRST',
  'addcdiv': 'STD_PROMOTE',
  'addcdiv_': 'EQ_FIRST',
  'addcmul': 'STD_PROMOTE',
  'addcmul_': 'EQ_FIRST',
  'addmm': 'MATMUL_2ND_3RD',
  'addmm_': 'EQ_FIRST',
  'addmv': 'PICK_1ST_2ND',
  'addmv_': 'EQ_FIRST',
  'addr': 'JOIN_2_3',
  'addr_': 'EQ_FIRST',
  'alias': 'EQ_FIRST',
  'align_to': 'ALL <1>',
  'all': 'ALL <>',
  'alpha_dropout': 'EQ_FIRST',
  'alpha_dropout_': 'EQ_FIRST',
  'amax': 'ALL <>',
  'amin': 'ALL <>',
  'angle': 'EQ_FIRST',
  'any': 'ALL <>',
  'arccos': 'EQ_FIRST',
  'arccos_': 'EQ_FIRST',
  'arccosh': 'EQ_FIRST',
  'arccosh_': 'EQ_FIRST',
  'arcsin': 'EQ_FIRST',
  'arcsin_': 'EQ_FIRST',
  'arcsinh': 'EQ_FIRST',
  'arcsinh_': 'EQ_FIRST',
  'arctan': 'EQ_FIRST',
  'arctan_': 'EQ_FIRST',
  'arctanh': 'EQ_FIRST',
  'arctanh_': 'EQ_FIRST',
  'argmax': 'ALL <>',
  'argmin': 'ALL <>',
  'argsort': 'EQ_FIRST',
  'as_strided': 'ALL <>',
  'as_strided_': 'ALL <>',
  'asin': 'EQ_FIRST',
  'asin_': 'EQ_FIRST',
  'asinh': 'EQ_FIRST',
  'asinh_': 'EQ_FIRST',
  'atan': 'EQ_FIRST',
  'atan2': 'STD_PROMOTE',
  'atan2_': 'EQ_FIRST',
  'atan_': 'EQ_FIRST',
  'atanh': 'EQ_FIRST',
  'atanh_': 'EQ_FIRST',
  'baddbmm': 'MATMUL_2ND_3RD',
  'baddbmm_': 'EQ_FIRST',
  'batch_norm': 'EQ_FIRST',
  'bernoulli': 'EQ_FIRST',
  'bernoulli.p': 'EQ_FIRST',
  'bernoulli_.Tensor': 'EQ_FIRST',
  'bernoulli_.float': 'EQ_FIRST',
  'binary_cross_entropy_backward': 'EQ_SECOND',
  'binomial': 'STD_PROMOTE',
  'bitwise_left_shift.Scalar_Tensor': 'EQ_FIRST',
  'bitwise_left_shift.Tensor': 'STD_PROMOTE',
  'bitwise_left_shift.Tensor_Scalar': 'EQ_FIRST',
  'bitwise_left_shift_.Tensor': 'EQ_FIRST',
  'bitwise_left_shift_.Tensor_Scalar': 'EQ_FIRST',
  'bitwise_right_shift.Scalar_Tensor': 'EQ_FIRST',
  'bitwise_right_shift.Tensor': 'STD_PROMOTE',
  'bitwise_right_shift.Tensor_Scalar': 'EQ_FIRST',
  'bitwise_right_shift_.Tensor': 'EQ_FIRST',
  'bitwise_right_shift_.Tensor_Scalar': 'EQ_FIRST',
  'bmm': 'MUL_1ST_2ND',
  'broadcast_to': 'ALL <>',
  'bucketize.Scalar': 'ALL <>',
  'bucketize.Tensor': 'EQ_FIRST',
  'cauchy_': 'EQ_FIRST',
  'cdist': 'MULT_1ST_2ND',
  'ceil': 'EQ_FIRST',
  'ceil_': 'EQ_FIRST',
  'chain_matmul': 'MUL_1ST_2ND',
  'channel_shuffle': 'EQ_FIRST',
  'cholesky': 'EQ_FIRST',
  'cholesky_inverse': 'EQ_FIRST',
  'clamp': 'EQ_FIRST',
  'clamp_': 'EQ_FIRST',
  'clamp_max': 'EQ_FIRST',
  'clamp_max.Tensor': 'STD_PROMOTE',
  'clamp_max_': 'EQ_FIRST',
  'clamp_max_.Tensor': 'EQ_FIRST',
  'clamp_min': 'EQ_FIRST',
  'clamp_min.Tensor': 'STD_PROMOTE',
  'clamp_min_': 'EQ_FIRST',
  'clamp_min_.Tensor': 'EQ_FIRST',
  'clip': 'EQ_FIRST',
  'clip_': 'EQ_FIRST',
  'clone': 'EQ_FIRST',
  'combinations': 'PAD1',
  'complex': 'STD_PROMOTE',
  'conj': 'EQ_FIRST',
  'conj_physical': 'EQ_FIRST',
  'conj_physical_': 'EQ_FIRST',
  'constant_pad_nd': 'EQ_FIRST',
  'contiguous': 'EQ_FIRST',
  'copy_': 'EQ_FIRST',
  'copysign.Scalar': 'EQ_FIRST',
  'copysign.Tensor': 'STD_PROMOTE',
  'copysign_.Scalar': 'EQ_FIRST',
  'copysign_.Tensor': 'EQ_FIRST',
  'cos': 'EQ_FIRST',
  'cos_': 'EQ_FIRST',
  'cosh': 'EQ_FIRST',
  'cosh_': 'EQ_FIRST',
  'cosine_embedding_loss': 'ALL <>',
  'count_nonzero': 'ALL <>',
  'count_nonzero.dim_IntList': 'ALL <>',
  'cumprod': 'EQ_FIRST',
  'cumprod_': 'EQ_FIRST',
  'cumsum': 'EQ_FIRST',
  'cumsum_': 'EQ_FIRST',
  'data': 'EQ_FIRST',
  'deg2rad': 'EQ_FIRST',
  'deg2rad_': 'EQ_FIRST',
  'dequantize.self': 'EQ_FIRST',
  'det': 'DROP2',
  'detach': 'EQ_FIRST',
  'detach_': 'EQ_FIRST',
  'digamma': 'EQ_FIRST',
  'digamma_': 'EQ_FIRST',
  'dist': 'ALL <>',
  'div.Scalar': 'EQ_FIRST',
  'div.Scalar_mode': 'EQ_FIRST',
  'div.Tensor': 'STD_PROMOTE',
  'div.Tensor_mode': 'STD_PROMOTE',
  'div_.Scalar': 'EQ_FIRST',
  'div_.Scalar_mode': 'EQ_FIRST',
  'div_.Tensor': 'EQ_FIRST',
  'div_.Tensor_mode': 'EQ_FIRST',
  'divide.Scalar': 'EQ_FIRST',
  'divide.Scalar_mode': 'EQ_FIRST',
  'divide.Tensor': 'STD_PROMOTE',
  'divide.Tensor_mode': 'STD_PROMOTE',
  'divide_.Scalar': 'EQ_FIRST',
  'divide_.Scalar_mode': 'EQ_FIRST',
  'divide_.Tensor': 'EQ_FIRST',
  'divide_.Tensor_mode': 'EQ_FIRST',
  'dot': 'ALL <>',
  'dropout': 'EQ_FIRST',
  'dropout_': 'EQ_FIRST',
  'elu': 'EQ_FIRST',
  'elu_': 'EQ_FIRST',
  'elu_backward': 'STD_PROMOTE',
  'empty_like': 'EQ_FIRST',
  'eq.Scalar': 'EQ_FIRST',
  'eq.Tensor': 'STD_PROMOTE',
  'eq_.Scalar': 'EQ_FIRST',
  'eq_.Tensor': 'EQ_FIRST',
  'erf': 'EQ_FIRST',
  'erf_': 'EQ_FIRST',
  'erfc': 'EQ_FIRST',
  'erfc_': 'EQ_FIRST',
  'erfinv': 'EQ_FIRST',
  'erfinv_': 'EQ_FIRST',
  'exp': 'EQ_FIRST',
  'exp2': 'EQ_FIRST',
  'exp2_': 'EQ_FIRST',
  'exp_': 'EQ_FIRST',
  'expand': 'ALL <>',
  'expand_as': 'EQ_SECOND',
  'expm1': 'EQ_FIRST',
  'expm1_': 'EQ_FIRST',
  'exponential_': 'EQ_FIRST',
  'fake_quantize_per_tensor_affine': 'EQ_FIRST',
  'fbgemm_pack_gemm_matrix_fp16': 'ALL <8>',
  'feature_alpha_dropout': 'EQ_FIRST',
  'feature_alpha_dropout_': 'EQ_FIRST',
  'feature_dropout': 'EQ_FIRST',
  'feature_dropout_': 'EQ_FIRST',
  'fft_fft': 'EQ_FIRST',
  'fft_fftn': 'EQ_FIRST',
  'fft_fftshift': 'EQ_FIRST',
  'fft_ifft': 'EQ_FIRST',
  'fft_ifftn': 'EQ_FIRST',
  'fft_ifftshift': 'EQ_FIRST',
  'fill_.Scalar': 'EQ_FIRST',
  'fill_.Tensor': 'EQ_FIRST',
  'fill_diagonal_': 'EQ_FIRST',
  'fix': 'EQ_FIRST',
  'fix_': 'EQ_FIRST',
  'flatten.using_ints': 'EQ_FIRST',
  'flip': 'EQ_FIRST',
  'fliplr': 'EQ_FIRST',
  'flipud': 'EQ_FIRST',
  'float_power.Scalar': 'EQ_FIRST',
  'float_power.Tensor_Scalar': 'EQ_FIRST',
  'float_power.Tensor_Tensor': 'STD_PROMOTE',
  'floor': 'EQ_FIRST',
  'floor_': 'EQ_FIRST',
  'floor_divide': 'STD_PROMOTE',
  'floor_divide.Scalar': 'EQ_FIRST',
  'floor_divide_.Scalar': 'EQ_FIRST',
  'floor_divide_.Tensor': 'EQ_FIRST',
  'fmax': 'STD_PROMOTE',
  'fmin': 'STD_PROMOTE',
  'fmod.Scalar': 'EQ_FIRST',
  'fmod.Tensor': 'STD_PROMOTE',
  'fmod_.Scalar': 'EQ_FIRST',
  'fmod_.Tensor': 'EQ_FIRST',
  'frac': 'EQ_FIRST',
  'frac_': 'EQ_FIRST',
  'frobenius_norm': 'ALL <>',
  'frobenius_norm.dim': 'ALL <>',
  'full_like': 'EQ_FIRST',
  'ge.Scalar': 'EQ_FIRST',
  'ge.Tensor': 'STD_PROMOTE',
  'ge_.Scalar': 'EQ_FIRST',
  'ge_.Tensor': 'EQ_FIRST',
  'gelu': 'EQ_FIRST',
  'gelu_backward': 'STD_PROMOTE',
  'glu_backward': 'EQ_SECOND',
  'greater.Scalar': 'EQ_FIRST',
  'greater.Tensor': 'STD_PROMOTE',
  'greater_.Scalar': 'EQ_FIRST',
  'greater_.Tensor': 'EQ_FIRST',
  'greater_equal.Scalar': 'EQ_FIRST',
  'greater_equal.Tensor': 'STD_PROMOTE',
  'greater_equal_.Scalar': 'EQ_FIRST',
  'greater_equal_.Tensor': 'EQ_FIRST',
  'gt.Scalar': 'EQ_FIRST',
  'gt.Tensor': 'STD_PROMOTE',
  'gt_.Scalar': 'EQ_FIRST',
  'gt_.Tensor': 'EQ_FIRST',
  'hardshrink': 'EQ_FIRST',
  'hardshrink_backward': 'STD_PROMOTE',
  'hardsigmoid': 'EQ_FIRST',
  'hardsigmoid_': 'EQ_FIRST',
  'hardsigmoid_backward': 'STD_PROMOTE',
  'hardswish': 'EQ_FIRST',
  'hardswish_': 'EQ_FIRST',
  'hardswish_backward': 'STD_PROMOTE',
  'hardtanh': 'EQ_FIRST',
  'hardtanh_': 'EQ_FIRST',
  'hardtanh_backward': 'STD_PROMOTE',
  'heaviside': 'STD_PROMOTE',
  'heaviside_': 'EQ_FIRST',
  'hinge_embedding_loss': 'ALL <>',
  'histc': 'ALL <1>',
  'huber_loss': 'ALL <>',
  'huber_loss_backward': 'STD_PROMOTE',
  'hypot': 'STD_PROMOTE',
  'hypot_': 'EQ_FIRST',
  'i0': 'EQ_FIRST',
  'i0_': 'EQ_FIRST',
  'igamma': 'STD_PROMOTE',
  'igamma_': 'EQ_FIRST',
  'igammac': 'STD_PROMOTE',
  'igammac_': 'EQ_FIRST',
  'infinitely_differentiable_gelu_backward': 'EQ_SECOND',
  'inverse': 'EQ_FIRST',
  'isclose': 'STD_PROMOTE',
  'isfinite': 'EQ_FIRST',
  'isin.Scalar_Tensor': 'ALL <>',
  'isin.Tensor_Scalar': 'EQ_FIRST',
  'isin.Tensor_Tensor': 'EQ_FIRST',
  'isinf': 'EQ_FIRST',
  'isnan': 'EQ_FIRST',
  'isneginf': 'EQ_FIRST',
  'isposinf': 'EQ_FIRST',
  'isreal': 'EQ_FIRST',
  'kl_div': 'ALL <>',
  'kl_div_backward': 'STD_PROMOTE',
  'kron': 'MULLAST_1ST_2ND',
  'l1_loss': 'ALL <>',
  'l1_loss_backward': 'STD_PROMOTE',
  'ldexp.Tensor': 'STD_PROMOTE',
  'ldexp_': 'EQ_FIRST',
  'le.Scalar': 'EQ_FIRST',
  'le.Tensor': 'STD_PROMOTE',
  'le_.Scalar': 'EQ_FIRST',
  'le_.Tensor': 'EQ_FIRST',
  'leaky_relu': 'EQ_FIRST',
  'leaky_relu_': 'EQ_FIRST',
  'leaky_relu_backward': 'STD_PROMOTE',
  'lerp.Scalar': 'STD_PROMOTE',
  'lerp.Tensor': 'STD_PROMOTE',
  'lerp_.Scalar': 'EQ_FIRST',
  'lerp_.Tensor': 'EQ_FIRST',
  'less.Scalar': 'EQ_FIRST',
  'less.Tensor': 'STD_PROMOTE',
  'less_.Scalar': 'EQ_FIRST',
  'less_.Tensor': 'EQ_FIRST',
  'less_equal.Scalar': 'EQ_FIRST',
  'less_equal.Tensor': 'STD_PROMOTE',
  'less_equal_.Scalar': 'EQ_FIRST',
  'less_equal_.Tensor': 'EQ_FIRST',
  'lgamma': 'EQ_FIRST',
  'lgamma_': 'EQ_FIRST',
  'linalg_cholesky': 'EQ_FIRST',
  'linalg_cond': 'DROP2',
  'linalg_det': 'DROP2',
  'linalg_eigvals': 'DROP1',
  'linalg_householder_product': 'EQ_FIRST',
  'linalg_inv': 'EQ_FIRST',
  'linalg_matrix_power': 'EQ_FIRST',
  'linalg_matrix_rank': 'DROP2',
  'linalg_multi_dot': 'MUL_1ST_2ND',
  'linalg_tensorinv': 'EQ_FIRST',
  'linalg_vector_norm': 'ALL <>',
  'linear': 'MULT_1ST_2ND',
  'log': 'EQ_FIRST',
  'log10': 'EQ_FIRST',
  'log10_': 'EQ_FIRST',
  'log1p': 'EQ_FIRST',
  'log1p_': 'EQ_FIRST',
  'log2': 'EQ_FIRST',
  'log2_': 'EQ_FIRST',
  'log_': 'EQ_FIRST',
  'log_normal_': 'EQ_FIRST',
  'log_sigmoid': 'EQ_FIRST',
  'log_sigmoid_backward': 'STD_PROMOTE',
  'log_softmax.int': 'EQ_FIRST',
  'logaddexp': 'STD_PROMOTE',
  'logaddexp2': 'STD_PROMOTE',
  'logcumsumexp': 'EQ_FIRST',
  'logdet': 'DROP2',
  'logical_and': 'STD_PROMOTE',
  'logical_and_': 'EQ_FIRST',
  'logical_not': 'EQ_FIRST',
  'logical_not_': 'EQ_FIRST',
  'logical_or': 'STD_PROMOTE',
  'logical_or_': 'EQ_FIRST',
  'logical_xor': 'STD_PROMOTE',
  'logical_xor_': 'EQ_FIRST',
  'logit': 'EQ_FIRST',
  'logit_': 'EQ_FIRST',
  'logit_backward': 'STD_PROMOTE',
  'logsumexp': 'ALL <>',
  'lt.Scalar': 'EQ_FIRST',
  'lt.Tensor': 'STD_PROMOTE',
  'lt_.Scalar': 'EQ_FIRST',
  'lt_.Tensor': 'EQ_FIRST',
  'margin_ranking_loss': 'ALL <>',
  'masked_fill.Scalar': 'STD_PROMOTE',
  'masked_fill.Tensor': 'STD_PROMOTE',
  'masked_fill_.Scalar': 'EQ_FIRST',
  'masked_fill_.Tensor': 'EQ_FIRST',
  'masked_scatter': 'PROMOTE_1_2',
  'masked_scatter_': 'EQ_FIRST',
  'matmul': 'MUL_1ST_2ND',
  'matrix_exp': 'EQ_FIRST',
  'matrix_exp_backward': 'EQ_FIRST',
  'matrix_power': 'EQ_FIRST',
  'matrix_rank': 'DROP2',
  'matrix_rank.tol': 'DROP2',
  'max': 'ALL <>',
  'max.other': 'STD_PROMOTE',
  'maximum': 'STD_PROMOTE',
  'mean': 'ALL <>',
  'mean.dim': 'ALL <>',
  'median': 'ALL <>',
  'min': 'ALL <>',
  'min.other': 'STD_PROMOTE',
  'minimum': 'STD_PROMOTE',
  'mish': 'EQ_FIRST',
  'mish_': 'EQ_FIRST',
  'mish_backward': 'STD_PROMOTE',
  'mm': 'MUL_1ST_2ND',
  'moveaxis.int': 'EQ_FIRST',
  'moveaxis.intlist': 'EQ_FIRST',
  'movedim.int': 'EQ_FIRST',
  'movedim.intlist': 'EQ_FIRST',
  'mse_loss': 'ALL <>',
  'mse_loss_backward': 'STD_PROMOTE',
  'msort': 'EQ_FIRST',
  'mul.Scalar': 'EQ_FIRST',
  'mul.Tensor': 'STD_PROMOTE',
  'mul_.Scalar': 'EQ_FIRST',
  'mul_.Tensor': 'EQ_FIRST',
  'multiply.Scalar': 'EQ_FIRST',
  'multiply.Tensor': 'STD_PROMOTE',
  'multiply_.Scalar': 'EQ_FIRST',
  'multiply_.Tensor': 'EQ_FIRST',
  'mv': 'MUL_1ST_2ND',
  'mvlgamma': 'EQ_FIRST',
  'mvlgamma_': 'EQ_FIRST',
  'nan_to_num': 'EQ_FIRST',
  'nan_to_num_': 'EQ_FIRST',
  'nanmedian': 'ALL <>',
  'nanquantile': 'EQ_SECOND',
  'nanquantile.scalar': 'ALL <>',
  'nansum': 'ALL <>',
  'nansum.dim_IntList': 'ALL <>',
  'ne.Scalar': 'EQ_FIRST',
  'ne.Tensor': 'STD_PROMOTE',
  'ne_.Scalar': 'EQ_FIRST',
  'ne_.Tensor': 'EQ_FIRST',
  'neg': 'EQ_FIRST',
  'neg_': 'EQ_FIRST',
  'negative': 'EQ_FIRST',
  'negative_': 'EQ_FIRST',
  'new_empty': 'ALL <>',
  'new_empty_strided': 'ALL <>',
  'new_full': 'ALL <>',
  'new_ones': 'ALL <>',
  'new_zeros': 'ALL <>',
  'nextafter': 'STD_PROMOTE',
  'nextafter_': 'EQ_FIRST',
  'norm.Scalar': 'ALL <>',
  'norm.ScalarOpt_dim': 'ALL <>',
  'normal.Tensor_float': 'EQ_FIRST',
  'normal.float_Tensor': 'EQ_FIRST',
  'normal_': 'EQ_FIRST',
  'not_equal.Scalar': 'EQ_FIRST',
  'not_equal.Tensor': 'STD_PROMOTE',
  'not_equal_.Scalar': 'EQ_FIRST',
  'not_equal_.Tensor': 'EQ_FIRST',
  'nuclear_norm': 'ALL <>',
  'ones_like': 'EQ_FIRST',
  'orgqr': 'EQ_FIRST',
  'ormqr': 'EQ_THIRD',
  'permute': 'ALL <>',
  'pixel_shuffle': 'EQ_FIRST',
  'pixel_unshuffle': 'EQ_FIRST',
  'poisson': 'EQ_FIRST',
  'poisson_nll_loss': 'ALL <>',
  'polar': 'STD_PROMOTE',
  'polygamma': 'EQ_FIRST',
  'polygamma_': 'EQ_FIRST',
  'positive': 'EQ_FIRST',
  'pow.Scalar': 'EQ_FIRST',
  'pow.Tensor_Scalar': 'EQ_FIRST',
  'pow.Tensor_Tensor': 'STD_PROMOTE',
  'pow_.Scalar': 'EQ_FIRST',
  'pow_.Tensor': 'EQ_FIRST',
  'prelu': 'EQ_FIRST',
  'prod': 'ALL <>',
  'quantile': 'EQ_SECOND',
  'quantile.scalar': 'ALL <>',
  'rad2deg': 'EQ_FIRST',
  'rad2deg_': 'EQ_FIRST',
  'rand_like': 'EQ_FIRST',
  'randint_like': 'EQ_FIRST',
  'randn_like': 'EQ_FIRST',
  'random_': 'EQ_FIRST',
  'random_.from': 'EQ_FIRST',
  'random_.to': 'EQ_FIRST',
  'reciprocal': 'EQ_FIRST',
  'reciprocal_': 'EQ_FIRST',
  'refine_names': 'EQ_FIRST',
  'relu': 'EQ_FIRST',
  'relu6': 'EQ_FIRST',
  'relu6_': 'EQ_FIRST',
  'relu_': 'EQ_FIRST',
  'remainder.Scalar': 'EQ_FIRST',
  'remainder.Scalar_Tensor': 'EQ_FIRST',
  'remainder.Tensor': 'STD_PROMOTE',
  'remainder_.Scalar': 'EQ_FIRST',
  'remainder_.Tensor': 'EQ_FIRST',
  'rename': 'EQ_FIRST',
  'rename_': 'EQ_FIRST',
  'repeat': 'ALL <>',
  'requires_grad_': 'EQ_FIRST',
  'reshape': 'ALL <>',
  'reshape_as': 'EQ_SECOND',
  'resize_': 'ALL <>',
  'resize_as_': 'EQ_SECOND',
  'resolve_conj': 'EQ_FIRST',
  'round': 'EQ_FIRST',
  'round_': 'EQ_FIRST',
  'rrelu': 'EQ_FIRST',
  'rrelu_': 'EQ_FIRST',
  'rrelu_with_noise': 'EQ_FIRST',
  'rrelu_with_noise_': 'EQ_FIRST',
  'rrelu_with_noise_backward': 'PROMOTE_1_2',
  'rsqrt': 'EQ_FIRST',
  'rsqrt_': 'EQ_FIRST',
  'rsub.Scalar': 'EQ_FIRST',
  'rsub.Tensor': 'STD_PROMOTE',
  'searchsorted.Scalar': 'ALL <>',
  'searchsorted.Tensor': 'EQ_SECOND',
  'selu': 'EQ_FIRST',
  'selu_': 'EQ_FIRST',
  'set_': 'ALL <0>',
  'set_.source_Tensor': 'EQ_SECOND',
  'sgn': 'EQ_FIRST',
  'sgn_': 'EQ_FIRST',
  'sigmoid': 'EQ_FIRST',
  'sigmoid_': 'EQ_FIRST',
  'sigmoid_backward': 'STD_PROMOTE',
  'sign': 'EQ_FIRST',
  'sign_': 'EQ_FIRST',
  'signbit': 'EQ_FIRST',
  'silu': 'EQ_FIRST',
  'silu_': 'EQ_FIRST',
  'silu_backward': 'STD_PROMOTE',
  'sin': 'EQ_FIRST',
  'sin_': 'EQ_FIRST',
  'sinc': 'EQ_FIRST',
  'sinc_': 'EQ_FIRST',
  'sinh': 'EQ_FIRST',
  'sinh_': 'EQ_FIRST',
  'slice.Tensor': 'EQ_FIRST',
  'smooth_l1_loss': 'ALL <>',
  'smooth_l1_loss_backward': 'STD_PROMOTE',
  'soft_margin_loss': 'ALL <>',
  'soft_margin_loss_backward': 'STD_PROMOTE',
  'softmax.int': 'EQ_FIRST',
  'softplus': 'EQ_FIRST',
  'softplus_backward': 'PROMOTE_1_2',
  'softshrink': 'EQ_FIRST',
  'softshrink_backward': 'STD_PROMOTE',
  'special_digamma': 'EQ_FIRST',
  'special_entr': 'EQ_FIRST',
  'special_erf': 'EQ_FIRST',
  'special_erfc': 'EQ_FIRST',
  'special_erfcx': 'EQ_FIRST',
  'special_erfinv': 'EQ_FIRST',
  'special_exp2': 'EQ_FIRST',
  'special_expit': 'EQ_FIRST',
  'special_expm1': 'EQ_FIRST',
  'special_gammaln': 'EQ_FIRST',
  'special_i0': 'EQ_FIRST',
  'special_i0e': 'EQ_FIRST',
  'special_i1': 'EQ_FIRST',
  'special_i1e': 'EQ_FIRST',
  'special_log1p': 'EQ_FIRST',
  'special_logit': 'EQ_FIRST',
  'special_ndtr': 'EQ_FIRST',
  'special_ndtri': 'EQ_FIRST',
  'special_psi': 'EQ_FIRST',
  'special_round': 'EQ_FIRST',
  'special_sinc': 'EQ_FIRST',
  'special_xlog1py': 'STD_PROMOTE',
  'special_xlog1py.other_scalar': 'EQ_FIRST',
  'special_xlog1py.self_scalar': 'EQ_FIRST',
  'special_zeta': 'STD_PROMOTE',
  'special_zeta.other_scalar': 'EQ_FIRST',
  'special_zeta.self_scalar': 'EQ_FIRST',
  'sqrt': 'EQ_FIRST',
  'sqrt_': 'EQ_FIRST',
  'square': 'EQ_FIRST',
  'square_': 'EQ_FIRST',
  'std': 'ALL <>',
  'std.correction': 'ALL <>',
  'std.dim': 'ALL <>',
  'sub.Scalar': 'EQ_FIRST',
  'sub.Tensor': 'STD_PROMOTE',
  'sub_.Scalar': 'EQ_FIRST',
  'sub_.Tensor': 'EQ_FIRST',
  'subtract.Scalar': 'EQ_FIRST',
  'subtract.Tensor': 'STD_PROMOTE',
  'subtract_.Scalar': 'EQ_FIRST',
  'subtract_.Tensor': 'EQ_FIRST',
  'sum': 'ALL <>',
  'sum.dim_IntList': 'ALL <>',
  'sum_to_size': 'ALL <>',
  'swapaxes': 'EQ_FIRST',
  'swapaxes_': 'EQ_FIRST',
  'swapdims': 'EQ_FIRST',
  'swapdims_': 'EQ_FIRST',
  'tan': 'EQ_FIRST',
  'tan_': 'EQ_FIRST',
  'tanh': 'EQ_FIRST',
  'tanh_': 'EQ_FIRST',
  'tanh_backward': 'STD_PROMOTE',
  'threshold': 'EQ_FIRST',
  'threshold_': 'EQ_FIRST',
  'threshold_backward': 'STD_PROMOTE',
  'tile': 'EQ_FIRST',
  'to.device': 'EQ_FIRST',
  'to.dtype': 'EQ_FIRST',
  'to.dtype_layout': 'EQ_FIRST',
  'to.other': 'EQ_FIRST',
  'to_sparse': 'EQ_FIRST',
  'to_sparse.sparse_dim': 'EQ_FIRST',
  'trace': 'ALL <>',
  'transpose.int': 'EQ_FIRST',
  'transpose_': 'EQ_FIRST',
  'tril': 'EQ_FIRST',
  'tril_': 'EQ_FIRST',
  'triplet_margin_loss': 'ALL <>',
  'triu': 'EQ_FIRST',
  'triu_': 'EQ_FIRST',
  'true_divide.Scalar': 'EQ_FIRST',
  'true_divide.Tensor': 'STD_PROMOTE',
  'true_divide_.Scalar': 'EQ_FIRST',
  'true_divide_.Tensor': 'EQ_FIRST',
  'trunc': 'EQ_FIRST',
  'trunc_': 'EQ_FIRST',
  'type_as': 'EQ_FIRST',
  'unfold': 'PAD1',
  'uniform_': 'EQ_FIRST',
  'var': 'ALL <>',
  'var.correction': 'ALL <>',
  'var.dim': 'ALL <>',
  'vdot': 'ALL <>',
  'view': 'ALL <>',
  'view_as': 'EQ_SECOND',
  'view_as_complex': 'DROP1',
  'xlogy.Scalar_Other': 'EQ_FIRST',
  'xlogy.Scalar_Self': 'EQ_FIRST',
  'xlogy.Tensor': 'STD_PROMOTE',
  'xlogy_.Scalar_Other': 'EQ_FIRST',
  'xlogy_.Tensor': 'EQ_FIRST',
  'zero_': 'EQ_FIRST',
  'zeros_like': 'EQ_FIRST',
}
